source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      order: 100
gems:
#  - jekyll-mentions cannot be used since it replaces annotations in java code with links to their github user counterparts :)
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
name: TracEE
url: http://www.tracee.io

sass:
    sass_dir: assets/css

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables", "with_toc_data"]


highlighter: pygments
#description: TODO: A description for your blog
